version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: 3.6.9
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            mkdir --parents test-results/unittest
            python -m xmlrunner --output test-results/unittest
          name: unittest
      - run:
          command: |
            mkdir artifacts
            python -m coverage run -m unittest
            python -m coverage report > artifacts/coverage.txt
          name: coverage.py
      - run:
          command: |
            mkdir --parents test-results/pylint
            python -m pylint --output-format=junit src > test-results/pylint/pylint.xml
          name: pylint
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: artifacts

workflows:
  main:
    jobs:
      - build-and-test
